create table
  public.context (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    phone_number text null,
    long_term_context text null,
    short_term_context text null,
    constraint context_pkey primary key (id),
    constraint context_phone_number_fkey foreign key (phone_number) references phone_numbers (phone_number)
  ) tablespace pg_default;

create index if not exists context_phone_number_idx on public.context using btree (phone_number) tablespace pg_default;


CREATE OR REPLACE FUNCTION process_call_content()
RETURNS TRIGGER AS $$
DECLARE
    recording_url text;
    response json;
BEGIN
    recording_url := NEW.recording_url;

    -- Make an HTTP POST request to the edge function
    response := net.http_post(
    url := 'https://supabase.com/dashboard/project/wlvyfoydbvsbcfindisa/functions/process-call',
    body := jsonb_build_object('recording_url', recording_url)
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

create table
  public.calls (
    id bigint generated always as identity not null,
    call_sid text not null,
    status text not null,
    start_time timestamp with time zone not null,
    end_time timestamp with time zone null,
    duration integer null,
    recording_url text null,
    is_test_call boolean not null default false,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    from_number text null,
    to_number text null,
    constraint calls_pkey primary key (id),
    constraint calls_call_sid_key unique (call_sid),
    constraint calls_from_number_fkey foreign key (from_number) references phone_numbers (phone_number),
    constraint calls_to_number_fkey foreign key (to_number) references phone_numbers (phone_number)
  ) tablespace pg_default;

create trigger call_insert_trigger
after insert on calls for each row
execute function process_call_content ();

create table
  public.phone_numbers (
    user_id uuid null,
    phone_number text not null,
    is_verified boolean not null default false,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null default now(),
    is_ours boolean null,
    prefix text null,
    constraint phone_numbers_pkey primary key (phone_number),
    constraint phone_numbers_phone_number_key unique (phone_number),
    constraint phone_numbers_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;

  create table
  public.prompts (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    prompt text null,
    description text null,
    constraint prompts_pkey primary key (id)
  ) tablespace pg_default;


